// <auto-generated />
namespace DownieDrive.Businesslogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class reinit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reinit));
        
        string IMigrationMetadata.Id
        {
            get { return "201606171152107_reinit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
